import { Parking, Reservation, Stationnement, Subscription, SubscriptionPurchase, Invoice } from '../types';

export const mockParkings: Parking[] = [
  {
    id: '1',
    name: 'Parking Centre Ville',
    address: '15 Rue de la République, 75001 Paris',
    totalSpaces: 50,
    availableSpaces: 23,
    hourlyRate: 3.5,
    openingTime: '06:00',
    closingTime: '22:00',
    description: 'Parking sécurisé au cœur du centre ville',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: '2',
    name: 'Parking Gare du Nord',
    address: '18 Rue de Dunkerque, 75010 Paris',
    totalSpaces: 120,
    availableSpaces: 45,
    hourlyRate: 4.0,
    openingTime: '00:00',
    closingTime: '23:59',
    description: 'Parking 24/7 près de la gare',
    latitude: 48.8809,
    longitude: 2.3553,
    isAlwaysOpen: true,
  },
  {
    id: '3',
    name: 'Parking Tour Eiffel',
    address: '5 Avenue Anatole France, 75007 Paris',
    totalSpaces: 80,
    availableSpaces: 12,
    hourlyRate: 5.0,
    openingTime: '07:00',
    closingTime: '23:00',
    description: 'Parking touristique premium',
    latitude: 48.8584,
    longitude: 2.2945,
  },
  {
    id: '4',
    name: 'Parking Entreprise',
    address: '42 Avenue des Champs-Élysées, 75008 Paris',
    totalSpaces: 200,
    availableSpaces: 180,
    hourlyRate: 2.5,
    openingTime: '18:00',
    closingTime: '08:00',
    description: 'Parking d\'entreprise disponible en soirée et week-end',
    latitude: 48.8698,
    longitude: 2.3078,
    customSchedule: [
      { dayOfWeek: 1, openTime: '18:00', closeTime: '08:00' }, // Lundi soir -> Mardi matin
      { dayOfWeek: 2, openTime: '18:00', closeTime: '08:00' },
      { dayOfWeek: 3, openTime: '18:00', closeTime: '08:00' },
      { dayOfWeek: 4, openTime: '18:00', closeTime: '08:00' },
      { dayOfWeek: 5, openTime: '18:00', closeTime: '23:59' }, // Vendredi soir -> tout le week-end
      { dayOfWeek: 6, openTime: '00:00', closeTime: '23:59' }, // Samedi
      { dayOfWeek: 0, openTime: '00:00', closeTime: '23:59' }, // Dimanche
    ],
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'r1',
    parkingId: '1',
    parkingName: 'Parking Centre Ville',
    customerId: 'u1',
    customerName: 'Jean Dupont',
    customerEmail: 'jean.dupont@email.com',
    startTime: new Date('2025-11-24T09:00:00'),
    endTime: new Date('2025-11-24T12:00:00'),
    status: 'active',
    price: 10.5,
    hasEntered: true,
    entryTime: new Date('2025-11-24T09:15:00'),
  },
  {
    id: 'r2',
    parkingId: '1',
    parkingName: 'Parking Centre Ville',
    customerId: 'u2',
    customerName: 'Marie Martin',
    customerEmail: 'marie.martin@email.com',
    startTime: new Date('2025-11-24T14:00:00'),
    endTime: new Date('2025-11-24T18:00:00'),
    status: 'pending',
    price: 14.0,
    hasEntered: false,
  },
  {
    id: 'r3',
    parkingId: '2',
    parkingName: 'Parking Gare du Nord',
    customerId: 'u1',
    customerName: 'Pierre Durand',
    customerEmail: 'pierre.durand@email.com',
    startTime: new Date('2025-11-23T08:00:00'),
    endTime: new Date('2025-11-23T17:00:00'),
    status: 'completed',
    price: 36.0,
    hasEntered: true,
    entryTime: new Date('2025-11-23T08:05:00'),
    exitTime: new Date('2025-11-23T17:45:00'),
    penalty: 20,
    overstayDuration: 45,
  },
  {
    id: 'r4',
    parkingId: '3',
    parkingName: 'Parking Tour Eiffel',
    customerId: 'u3',
    customerName: 'Sophie Bernard',
    customerEmail: 'sophie.bernard@email.com',
    startTime: new Date('2025-11-24T10:00:00'),
    endTime: new Date('2025-11-24T15:00:00'),
    status: 'active',
    price: 25.0,
    hasEntered: true,
    entryTime: new Date('2025-11-24T10:00:00'),
  },
  {
    id: 'r5',
    parkingId: '2',
    parkingName: 'Parking Gare du Nord',
    customerId: 'u1',
    customerName: 'Jean Dupont',
    customerEmail: 'jean.dupont@email.com',
    startTime: new Date('2025-11-20T14:00:00'),
    endTime: new Date('2025-11-20T18:00:00'),
    status: 'completed',
    price: 16.0,
    hasEntered: false,
  },
];

export const mockStationnements: Stationnement[] = [
  {
    id: 's1',
    parkingId: '1',
    parkingName: 'Parking Centre Ville',
    vehiclePlate: 'AB-123-CD',
    customerId: 'u1',
    customerName: 'Jean Dupont',
    entryTime: new Date('2025-11-24T09:15:00'),
    reservationId: 'r1',
    isAuthorized: true,
  },
  {
    id: 's2',
    parkingId: '1',
    parkingName: 'Parking Centre Ville',
    vehiclePlate: 'EF-456-GH',
    customerId: 'u4',
    customerName: 'Inconnu',
    entryTime: new Date('2025-11-24T13:00:00'),
    isAuthorized: false,
  },
  {
    id: 's3',
    parkingId: '3',
    parkingName: 'Parking Tour Eiffel',
    vehiclePlate: 'IJ-789-KL',
    customerId: 'u3',
    customerName: 'Sophie Bernard',
    entryTime: new Date('2025-11-24T10:00:00'),
    reservationId: 'r4',
    isAuthorized: true,
  },
  {
    id: 's4',
    parkingId: '2',
    parkingName: 'Parking Gare du Nord',
    vehiclePlate: 'MN-012-OP',
    customerId: 'u5',
    customerName: 'Inconnu',
    entryTime: new Date('2025-11-24T02:00:00'),
    isAuthorized: false,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub1',
    name: 'Abonnement Mensuel',
    parkingId: '1',
    price: 120,
    duration: 30,
    benefits: ['Accès illimité', 'Place garantie', 'Pas de réservation nécessaire'],
  },
  {
    id: 'sub2',
    name: 'Abonnement Hebdomadaire',
    parkingId: '1',
    price: 35,
    duration: 7,
    benefits: ['Accès illimité pendant 7 jours'],
  },
  {
    id: 'sub3',
    name: 'Abonnement Mensuel Premium',
    parkingId: '2',
    price: 150,
    duration: 30,
    benefits: ['Accès 24/7', 'Place couverte', 'Service de voiturier'],
  },
  {
    id: 'sub4',
    name: 'Abonnement Week-end',
    parkingId: '3',
    price: 40,
    duration: 30,
    benefits: ['Accès tous les week-ends du mois'],
  },
];

export const mockSubscriptionPurchases: SubscriptionPurchase[] = [
  {
    id: 'sp1',
    subscriptionId: 'sub1',
    subscriptionName: 'Abonnement Mensuel',
    customerId: 'u1',
    customerName: 'Jean Dupont',
    startDate: new Date('2025-11-01'),
    endDate: new Date('2025-11-30'),
    status: 'active',
  },
  {
    id: 'sp2',
    subscriptionId: 'sub3',
    subscriptionName: 'Abonnement Mensuel Premium',
    customerId: 'u2',
    customerName: 'Marie Martin',
    startDate: new Date('2025-11-01'),
    endDate: new Date('2025-11-30'),
    status: 'active',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    reservationId: 'r3',
    customerId: 'u1',
    customerName: 'Pierre Durand',
    parkingName: 'Parking Gare du Nord',
    startTime: new Date('2025-11-23T08:00:00'),
    endTime: new Date('2025-11-23T17:00:00'),
    basePrice: 36.0,
    penalty: 20.0,
    totalPrice: 59.0, // 36 + 20 + (45min * 4€/h = 3€)
    createdAt: new Date('2025-11-23T17:45:00'),
    status: 'paid',
  },
  {
    id: 'inv2',
    reservationId: 'r5',
    customerId: 'u1',
    customerName: 'Jean Dupont',
    parkingName: 'Parking Gare du Nord',
    startTime: new Date('2025-11-20T14:00:00'),
    endTime: new Date('2025-11-20T18:00:00'),
    basePrice: 16.0,
    penalty: 0,
    totalPrice: 16.0,
    createdAt: new Date('2025-11-20T18:00:00'),
    status: 'paid',
  },
];

// ID de l'utilisateur connecté pour les données mock
export const CURRENT_USER_ID = 'u1';
export const CURRENT_USER_NAME = 'Jean Dupont';
export const CURRENT_USER_EMAIL = 'jean.dupont@email.com';
